baseURL = 'https://enchanting-sunburst-71a9df.netlify.app/'
languageCode = 'fr-fr'
title = 'Vincent Garcia'
theme = 'archie'
copyright = 'Â© Vincent Garcia'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5

[params]
mode="toggle"
useCDN=false
subtitle = "ğŸ‘¨â€ğŸ’» **DÃ©veloppeur** le jour, ğŸƒâ€â™‚ï¸ **coureur** la nuit et ğŸ‘¨â€ğŸ‘¦â€ğŸ‘¦ **papa** le temps qui reste."
customcss = ["css/override.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/intraordinaire"

[[params.social]]
name = "Strava"
icon = "activity"
url = "https://strava.com/athletes/intraordinaire"

[[params.social]]
name = "Spotify"
icon = "music"
url = "https://open.spotify.com/user/intraordinaire?si=992309dc21214833"


[[menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[menu.main]]
name = "Photos"
url = "/photos"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Ã€ propos"
url = "/a-propos"
weight = 4
